Dev2
go-park-mail-ru/2024_2_Team7 pull request #1
Opened 2024-09-27 17:37 UTC by source-Alexander-Rudenko

2024-09-27 19:35 UTC, reddiridabl666 commented on .gitignore
> +pkg
Правило хорошего тона - делать в конце файлов пустую строку

2024-09-27 19:37 UTC, reddiridabl666 commented on news-api/go.sum
go.mod надо класть в корень, он общий на весь проект

2024-09-27 19:42 UTC, reddiridabl666 commented on news-api/cmd/server/main.go
> +	c := cors.New(cors.Options{
Давай напишем свою миддлвару, которая будет проставлять CORS-хэдеры, не будем использовать стороннюю либу.

Вообще по проекту мы используем минимум сторонних либ, почти ничего нельзя, кроме того, что есть в примерах лекций

2024-09-27 19:45 UTC, reddiridabl666 commented on news-api/internal/auth/auth.go
> +	w.WriteHeader(http.StatusCreated)
Надо что-то возвращать фронту - как минимум, айди созданного пользователя

2024-09-27 19:46 UTC, reddiridabl666 commented on news-api/internal/auth/auth.go
> +		http.SetCookie(w, &http.Cookie{
Куку надо делать http-only

2024-09-27 19:48 UTC, reddiridabl666 commented on news-api/internal/auth/auth.go
> +		w.WriteHeader(http.StatusOK)
Надо после логина вернуть всю инфу по юзеру на фронт

2024-09-27 19:50 UTC, reddiridabl666 commented on news-api/internal/auth/auth.go
> +	cookie, err := r.Cookie("session_token")
session_token в константу

2024-09-27 19:52 UTC, reddiridabl666 commented on news-api/internal/auth/auth.go
> +	w.Write([]byte("Logged out successfully"))
Ну не просто строчку же слать) Общаемся только JSON-ами

2024-09-27 19:55 UTC, reddiridabl666 commented on news-api/cmd/server/main.go
> +	r.HandleFunc("/logout", auth.AuthMiddleware(auth.LogoutHandler)).Methods("POST")
auth.Middleware я бы как-нибудь более глобально применил - у вас потом будет миллион ручек, почти все из которых требуют логина.

Возможно, стоит сделать общую миддлвару с вайтлистом урлов, на которых не надо проверять сессию

2024-09-27 19:57 UTC, reddiridabl666 commented on news-api/internal/news/models.go
> +type News struct {
Давай назовем эту сущность Event. У нас все-таки проект не про новости, а про мероприятия.

2024-09-27 19:59 UTC, reddiridabl666 commented on news-api/internal/users/users.go
> +		return User{}, errors.New("user not found")
Стоит сделать типовые ошибки глобальными переменными в отдельном пакете, типа custom_errors. Так вам будет потом удобнее проверять на ошибки для возврата тех или иных http-статусов

2024-09-27 20:02 UTC, reddiridabl666 commented on news-api/internal/users/users.go
> +	if !exists || user.Password != password {
Пароли в базе должны храниться в хешированном виде. Но пока можно забить - вам аж в 7 лекции будут рассказывать

2024-09-27 20:03 UTC, reddiridabl666 commented on news-api/internal/users/users.go
> +var users = make(map[string]User)
Давай сделаем структуру с полем users, чтобы у нас не было глобальных переменных. Так будет проще в дальнейшем рефакторить на реализацию через СУБД

2024-09-27 20:04 UTC, reddiridabl666 commented on news-api/pkg/session/session.go
> +	expiration := time.Now().Add(30 * time.Minute)
`30 * time.Minute` в константу

2024-09-27 20:04 UTC, reddiridabl666 commented on news-api/pkg/session/session.go
> +func DeleteSession(token string) {
Пустую строчку между методами) Это бы поймал gofumpt

2024-09-27 20:05 UTC, reddiridabl666 commented on news-api/pkg/session/session.go
> +func GetExpiration() time.Time {
Зачем нужна эта функция? Почему не использовать вместо неё поле Expires у Session?

2024-09-27 20:08 UTC, reddiridabl666 commented on news-api/pkg/session/session.go
> +var sessions = make(map[string]Session)
Аналогично вынести в структуру, чтобы не было глобальных переменных

2024-09-27 20:09 UTC, reddiridabl666 commented on news-api/internal/auth/auth.go
> +func RegisterHandler(w http.ResponseWriter, r *http.Request) {
Набор хэндлеров по общей тематике обычно делают методами структуры. Соответственно, в полях этих структур лежат все необходимые зависимости (интерфейсы для взаимодействия с БД, например)

2024-09-28 09:04 UTC, reddiridabl666 commented on news-api/internal/news/news.go
> +}
Надо добавить больше мероприятий - и чтобы у них были реальные названия, описания и картинки. Помните о том, что вы делаете продукт

2024-09-28 09:05 UTC, reddiridabl666 commented on news-api/internal/news/models.go
> +	Date        string
У мероприятия может быть не одна дата - есть всякие выставки, фестивали, которые длятся больше одного дня. Еще, думаю, пользователю важно время, не только дата. Также недостает адреса - как пользователь будет знать, куда ему идти? В общем, надо тщательнее продумать модель данных

2024-09-28 09:08 UTC, reddiridabl666 commented on news-api/internal/news/news.go
> +func GetNewsHandler(w http.ResponseWriter, r *http.Request) {
Я не видел, как выглядит ваш дизайн, но мб стоит задуматься о нескольких подборках мероприятий. Скажем, "Новые", "Популярные", "Рекомендации" и т.д.

У вас ведь в продуктовых требованиях написано "ПодборкИ мероприятий", в множественном числе. Преподы могут докопаться на РК (у нас докапывались)

2024-09-28 15:35 UTC, reddiridabl666 requested changes

2024-09-28 15:35 UTC, reddiridabl666 commented on internal/auth/auth.go
> +	json.NewEncoder(w).Encode("logged out")
Это все еще просто строчка. Фронт вряд ли будет такое обрабатывать. Я бы сделал либо пустой JSON-объект, либо вообще ничего не отправлял. В принципе, фронту достаточно и статуса

2024-09-28 15:35 UTC, reddiridabl666 commented on internal/auth/middleware.go
> +func (h *Handler) GetEventsHandler(w http.ResponseWriter, r *http.Request) {
Как будто это не должно быть в файле middleware

2024-09-28 15:35 UTC, reddiridabl666 commented on internal/events/models.go
> +}
Давайте сделаем json-теги полям структур. Обычно в JSON используют либо camelCase, либо snake_case, а го по умолчанию будет парсить в PascalCase

2024-09-28 15:35 UTC, reddiridabl666 commented on session/session.go
> +	cookie, err := r.Cookie("session_token")
Константу сделали, а здесь не используете

2024-09-28 15:35 UTC, reddiridabl666 commented on internal/auth/auth.go
> +}
То, что сделали структуру хэндлера - хорошо, но лучше разделять зоны ответственности: пусть будет отдельная структура для юзеров и сессии и отдельная для ивентов

2024-09-28 15:35 UTC, reddiridabl666 commented on internal/users/models.go
> +}
Надо подумать о том, как пользователь регистрируется. Мб ему нужна почта? Конечно, вряд ли вы будете делать через неё подтверждение регистрации или восстановление пароля и никто от вас этого не просит, но мб имеет смысл спрашивать ее у пользователя при регистрации

2024-09-28 15:35 UTC, reddiridabl666 commented on internal/auth/auth.go
> +	json.NewEncoder(w).Encode(user)
Вы отправляете юзеру обратно пароль - не очень хорошо. Конечно, потом у вас будет https, но все еще лучше так не делать

Можно сделать отдельно структуру Credentials и структуру User

2024-09-28 15:35 UTC, reddiridabl666 commented on internal/events/events.go
> +			ImageURL:    "/static/images/Events1.jpg",
Картинки у вас на фронте хранятся?

2024-09-28 15:35 UTC, reddiridabl666 commented on internal/users/models.go
> +	users["semenov"] = User{Password: "123"}
Username не проставили юзерам

2024-09-28 15:35 UTC, reddiridabl666 commented on cmd/server/main.go
> +	r.HandleFunc("/", authHandler.GetEventsHandler).Methods("GET")
Нет ручки на проверку сессии. Получается, юзеру придется логиниться каждый раз при входе. Надо сделать ручку, в которой проверяется кука и возвращается информация о юзере, если кука валидная

2024-09-28 16:14 UTC, reddiridabl666 commented on cmd/server/main.go
> +	}
Плохо, что ручка на список мероприятий у вас спрятана за логином. Получается, новый пользователь ничего не увидит, зайдя на ваш сайт - только формы регистрации. Это отпугивает юзеров, надо, чтобы на сайте был какой-то контент без авторизации

2024-09-28 19:25 UTC, reddiridabl666 commented on internal/auth/middleware.go
> +		fmt.Println(r)
При логировании запроса таким образом в консоли получается нечитаемая каша, лучше логируйте отдельно метод и путь

2024-09-28 19:38 UTC, reddiridabl666 commented on cmd/server/main.go
> +	r.HandleFunc("/", authHandler.GetEventsHandler).Methods("GET")
"/" у апишек не делают, давай назовем эту ручку "/events"

2024-09-29 09:37 UTC, reddiridabl666 requested changes

2024-09-29 09:37 UTC, reddiridabl666 commented on internal/auth/auth.go
> +func (h *AuthHandler) CheckSessionHandler(w http.ResponseWriter, r *http.Request) {
Кстати, суффикс Handler я бы убрал у каждого метода - и так понятно, что это обработчики по сигнатуре

2024-09-29 09:37 UTC, reddiridabl666 commented on internal/events/events.go
> +	}
В принципе, так тоже можно, но обычно в таких случаях возвращают пустой массив и http.StatusNoContent

2024-09-29 09:37 UTC, reddiridabl666 commented on internal/users/models.go
> +	DateOfBirth string `json:"date_of_birth"`
А дата рождения точно нужна? Будут мероприятия с возрастными ограничениями? Помните, что чем проще регистрация, тем лучше. Может, имеет смысл сделать указание даты рождения опциональным

2024-09-29 09:37 UTC, reddiridabl666 commented on internal/users/models.go
> +	DateOfBirth string `json:"date_of_birth"`
Под разделить Credentials и User я имел в виду наоборот: Credentials - инфа, необходимая для логина, т.е. включает в себя пароль, а в User можно было сделать тег `json:"-"`, чтобы при парсинге не возвращать пароль

А еще часто разделяют структуры, которые парсят в JSON и структуры, которые хранят в базе, тк физическое представление данных не всегда на 100% маппится в логическое

Но пока можете не париться

2024-09-29 09:37 UTC, reddiridabl666 commented on internal/users/models.go
> +	ID          string `json:"id"`
А почему ID строчкой? Кажется, лучше числом, вы все равно везде числом его делаете, а не каким-нибудь UUID

2024-09-29 09:37 UTC, reddiridabl666 commented on internal/auth/auth.go
> +	json.NewEncoder(w).Encode(session)
А здесь надо возвращать не сессию, а полную инфу о юзере - имя, айди, почту и т.д.

2024-09-29 09:37 UTC, reddiridabl666 commented on session/session.go
> -		return nil, false
Возвращать nil в таких случаях - норма, могли бы не менять. Единственное - надо потом не забыть проверить на nil, а то паника будет

Конечно, так тоже норм, можете не править

2024-09-29 11:30 UTC, reddiridabl666 commented on internal/users/users.go
>  func (d *UserDB) AddUser(user User) {
Давай принимать юзера по указателю либо возвращать айди нового пользователя. Иначе фронт не получит айди пользователя при регистрации, только при следующем логине

2024-09-29 11:42 UTC, reddiridabl666 requested changes

2024-09-29 11:42 UTC, reddiridabl666 commented on internal/users/users.go
>  func (d *UserDB) GetUser(username string) User {
В методах, где структура не меняется, лучше принимать структуру (`d *UserDB`) по значению, а не по указателю. Не бойтесь лишних копирований - когда копировать немного, это быстрее, чем брать адрес.

По указателю имеет смысл принимать, если вы изменяете структуру в методе, или если она действительно большая и копировать дорого

А в ваших структура только мапки - они немного весят - там указатель на область данных и пара чисел

2024-09-29 11:42 UTC, reddiridabl666 commented on internal/users/users.go
>  	d.users[user.Username] = user
Жесть, чуть не забыл. Вы работаете в условиях конкурентности - стандартный HTTP-сервер создает много горутин, которые обрабатывают входящие запросы. Поэтому в методах, которые работают с мапами ОБЯЗАТЕЛЬНО должны использоваться мьютексы

Есть вариант использовать sync.Map, но я бы использовал sync.RWMutex в комбинации с обычной мапой

2024-09-29 19:55 UTC, reddiridabl666 commented on dockerfile
> +RUN go mod download
Кажется лишним - мы и так потом всё копируем + при выполнении go build модули сами скачаются

2024-09-30 05:20 UTC, reddiridabl666 commented on internal/events/event_test.go
> +			assert.Equal(t, tc.expectedStatus, resp.StatusCode)
Можно здесь использовать require вместо assert - тогда тест завершится, если проверка не пройдет. И можно будет убрать `if tc.expectedStatus == http.StatusOK`

2024-09-30 05:20 UTC, reddiridabl666 commented on internal/events/events.go
> +	defer h.EventDB.mu.RUnlock()
Работа с мьютексами должна происходить не в хэндлерах, а в методах EventDB. Контроль конкурентного доступа - зона ответственности БД, а не http-хэндлеров

В остальном мьютексы использованы правильно

2024-09-30 05:20 UTC, reddiridabl666 commented on session/session_test.go
> +	request *http.Request
Поле request не используется

2024-09-30 18:46 UTC, source-Alexander-Rudenko commented on dockerfile
> +RUN go mod download
Да, я прочитал что докер кэширует контейнеры и если mod не меняется, то он по новой не строит зависимости и быстрее собирается. Контейнер с фронтом сделал, наоборот, он каждый раз по новой строит и по итогу раза в два дольше чем бэк собирается.

2024-09-30 19:02 UTC, reddiridabl666 commented on internal/auth/middleware.go
> +		for _, path := range whitelist {
Тут раньше было логирование всего запроса целиком, мб сделаем какой-то базовый лог? Хотя бы просто метод и путь запроса.

Про нормальное логирование будут дальше рассказывать, но можно базово сделать сейчас, чтобы дебажить было легче. Мб поможет вам, когда будете править к РК

2024-10-01 01:09 UTC, merged